### ISSUE TITLE
I live in your walls

### ISSUE THREAD

**Issue by CalcoDev** [turtle4ever/Nerdvana-2DPlatformer#1]
> Use polygon colliders, unless you want people in your walls.
> -Sun Tzu, The Art of Game Dev

![walls](https://github.com/turtle4ever/Nerdvana-2DPlatformer/assets/89984030/65b3d723-3cb9-4de1-a59d-f01d04bcb8b2)
![walls2](https://github.com/turtle4ever/Nerdvana-2DPlatformer/assets/89984030/4695d7d2-4cd7-46ae-a7d6-40059dd952b0)
![walls3](https://github.com/turtle4ever/Nerdvana-2DPlatformer/assets/89984030/c8199f91-31e6-4279-82c3-d79323d5c2f1)

**Comment by turtle4ever** [comment]
Fight me in the sewers coward
